// Package bindgen generates Tide foreign bindings by introspecting a Go
// package's type information (ffi.md, RFC-0005). It is the `tide import`
// tool: given a Go import path it emits a deterministic `.td` declaration
// file of `extern` items a human then curates.
//
// Binding signatures are derived mechanically from go/types (D6) — Tide
// binds, it does not port (D3). The introspection uses the stdlib
// `go/importer` in "source" mode rather than golang.org/x/tools/go/
// packages, so the compiler stays dependency-free (the project's
// stdlib-only ethos); for the stdlib targets this epoch needs, source-mode
// importing gives the same full go/types information.
//
// The output is a *starting point a human owns*: unbindable symbols and
// guessed boundary-lifts are marked inline (`// UNBINDABLE` / `// GUESS`)
// for the curator, and the Go type checker re-verifies every binding at
// build time (the verify-don't-trust property; ffi.md).
package bindgen

import (
	"fmt"
	"go/importer"
	"go/token"
	"go/types"
	"sort"
	"strings"
)

// Generate introspects the Go package at importPath and returns the
// curated-starting-point Tide binding file as source text.
func Generate(importPath string) (string, error) {
	imp := importer.ForCompiler(token.NewFileSet(), "source", nil)
	pkg, err := imp.Import(importPath)
	if err != nil {
		return "", fmt.Errorf("bindgen: loading %q: %w", importPath, err)
	}
	g := &generator{pkg: pkg, path: importPath}
	return g.run(), nil
}

type generator struct {
	pkg  *types.Package
	path string // Go import path, e.g. "os/exec"
}

// run walks the package's exported scope and renders the binding file.
// Output order is deterministic: funcs (sorted), then types with their
// impl blocks (sorted) — so re-running produces a stable diff over the
// human's curation.
func (g *generator) run() string {
	scope := g.pkg.Scope()
	var funcs []*types.Func
	var named []*types.TypeName
	for _, name := range scope.Names() {
		obj := scope.Lookup(name)
		if !obj.Exported() {
			continue
		}
		switch o := obj.(type) {
		case *types.Func:
			funcs = append(funcs, o)
		case *types.TypeName:
			if _, ok := o.Type().(*types.Named); ok {
				named = append(named, o)
			}
		}
	}
	sort.Slice(funcs, func(i, j int) bool { return funcs[i].Name() < funcs[j].Name() })
	sort.Slice(named, func(i, j int) bool { return named[i].Name() < named[j].Name() })

	var b strings.Builder
	fmt.Fprintf(&b, "// Generated by `tide import %s`. Curate before use (ffi.md).\n", g.path)
	fmt.Fprintf(&b, "// A starting point a human owns — review every binding; the Go\n")
	fmt.Fprintf(&b, "// type checker re-verifies each at build time.\n\n")

	for _, fn := range funcs {
		b.WriteString(g.renderFunc(fn))
	}
	if len(funcs) > 0 && len(named) > 0 {
		b.WriteByte('\n')
	}
	for i, tn := range named {
		if i > 0 {
			b.WriteByte('\n')
		}
		b.WriteString(g.renderType(tn))
	}
	out := b.String()
	// An all-bail package (every exported symbol untranslatable) yields a
	// comment-only file with no declarations — the compiler would reject
	// that with E0112, so the round-trip property holds only for a file
	// with ≥1 binding. Make the emptiness explicit rather than emit a
	// silently-uncompilable file (ffi.md §"The generator").
	if !strings.Contains(out, "\nextern ") {
		out += "\n// No bindable symbols — every exported symbol bailed above.\n" +
			"// Nothing to compile; bind the needed Go shapes by hand or via an adapter.\n"
	}
	return out
}

// HasBindings reports whether generated output contains at least one
// `extern` declaration (vs an all-comment / all-bail report). The
// `tide import` command warns when false.
func HasBindings(src string) bool {
	return strings.Contains(src, "\nextern ")
}

// renderFunc renders a package-level function as an `extern func`, or a
// `// UNBINDABLE` comment naming the first untranslatable type.
func (g *generator) renderFunc(fn *types.Func) string {
	sig := fn.Type().(*types.Signature)
	name := tideName(fn.Name())
	params, perr := g.renderParams(sig)
	if perr != "" {
		return fmt.Sprintf("// UNBINDABLE %s: %s\n", name, perr)
	}
	ret, guess, rerr := g.renderResults(sig)
	if rerr != "" {
		return fmt.Sprintf("// UNBINDABLE %s: %s\n", name, rerr)
	}
	var out strings.Builder
	if guess != "" {
		fmt.Fprintf(&out, "// GUESS %s: %s\n", name, guess)
	}
	fmt.Fprintf(&out, "extern func %s(%s)%s @go(%q)\n",
		name, params, ret, g.path+"."+fn.Name())
	return out.String()
}

// renderType renders a named type as an opaque `extern type` handle plus
// an `extern impl` of its bindable exported methods.
func (g *generator) renderType(tn *types.TypeName) string {
	named := tn.Type().(*types.Named)
	var b strings.Builder
	fmt.Fprintf(&b, "extern type %s @go(%q)\n", tn.Name(), g.path+"."+tn.Name())

	var members []string
	for i := 0; i < named.NumMethods(); i++ {
		m := named.Method(i)
		if !m.Exported() {
			continue
		}
		members = append(members, g.renderMethod(m))
	}
	sort.Strings(members)
	if len(members) > 0 {
		fmt.Fprintf(&b, "\nextern impl %s {\n", tn.Name())
		for _, m := range members {
			b.WriteString("    ")
			b.WriteString(m)
			b.WriteByte('\n')
		}
		b.WriteString("}\n")
	}
	return b.String()
}

// renderMethod renders one method line (no leading indent), or a
// `// UNBINDABLE` comment when its signature is not translatable.
func (g *generator) renderMethod(m *types.Func) string {
	sig := m.Type().(*types.Signature)
	name := tideName(m.Name())
	params, perr := g.renderParams(sig)
	if perr != "" {
		return fmt.Sprintf("// UNBINDABLE %s: %s", name, perr)
	}
	ret, guess, rerr := g.renderResults(sig)
	if rerr != "" {
		return fmt.Sprintf("// UNBINDABLE %s: %s", name, rerr)
	}
	line := fmt.Sprintf("%s(%s)%s @go(%q)", name, params, ret, m.Name())
	if guess != "" {
		line += "  // GUESS: " + guess
	}
	return line
}

// renderParams renders a parameter list, or a non-empty reason string
// when a parameter type (or variadic) is untranslatable.
func (g *generator) renderParams(sig *types.Signature) (string, string) {
	tup := sig.Params()
	var parts []string
	for i := 0; i < tup.Len(); i++ {
		p := tup.At(i)
		// The final parameter of a variadic Go signature has type `[]T`;
		// bind it as Tide's variadic `...T` (ffi.md §Variadic).
		if sig.Variadic() && i == tup.Len()-1 {
			st, ok := p.Type().(*types.Slice)
			if !ok {
				return "", "variadic final parameter is not a slice"
			}
			tt, ok, reason := g.translate(st.Elem())
			if !ok {
				return "", fmt.Sprintf("param %s: %s", paramName(p, i), reason)
			}
			parts = append(parts, fmt.Sprintf("%s: ...%s", paramName(p, i), tt))
			continue
		}
		tt, ok, reason := g.translate(p.Type())
		if !ok {
			return "", fmt.Sprintf("param %s: %s", paramName(p, i), reason)
		}
		parts = append(parts, fmt.Sprintf("%s: %s", paramName(p, i), tt))
	}
	return strings.Join(parts, ", "), ""
}

// renderResults renders the Tide return annotation for a signature,
// applying the boundary lifts. Returns (annotation, guessNote, errReason);
// annotation is "" for a unit return. The leading ": " is included.
func (g *generator) renderResults(sig *types.Signature) (string, string, string) {
	res := sig.Results()
	switch res.Len() {
	case 0:
		return "", "", ""
	case 1:
		t := res.At(0).Type()
		if isErrorType(t) {
			return ": Result<unit, error>", "", "" // func(...) error
		}
		tt, ok, reason := g.translate(t)
		if !ok {
			return "", "", "return " + reason
		}
		return ": " + tt, "", ""
	case 2:
		a, b := res.At(0).Type(), res.At(1).Type()
		if isErrorType(b) { // (T, error) → Result<T, error>
			tt, ok, reason := g.translate(a)
			if !ok {
				return "", "", "return " + reason
			}
			return ": Result<" + tt + ", error>", "", ""
		}
		if isBasicKind(b, types.Bool) { // (T, bool) comma-ok → Option<T>
			tt, ok, reason := g.translate(a)
			if !ok {
				return "", "", "return " + reason
			}
			return ": Option<" + tt + ">", "(T, bool) → Option<T> — verify this is comma-ok, not a meaningful bool", ""
		}
		return "", "", "two non-error/bool results — not bindable"
	default:
		return "", "", fmt.Sprintf("%d results — arity ≥ 3 not bindable", res.Len())
	}
}

// translate maps a Go type to its Tide spelling. ok=false carries a
// human-readable reason naming the offending construct (the bail list).
func (g *generator) translate(t types.Type) (string, bool, string) {
	switch u := t.(type) {
	case *types.Basic:
		return translateBasic(u)
	case *types.Slice:
		et, ok, reason := g.translate(u.Elem())
		if !ok {
			return "", false, reason
		}
		return "[]" + et, true, ""
	case *types.Map:
		kt, ok, reason := g.translate(u.Key())
		if !ok {
			return "", false, reason
		}
		vt, ok, reason := g.translate(u.Elem())
		if !ok {
			return "", false, reason
		}
		return "Map<" + kt + ", " + vt + ">", true, ""
	case *types.Chan:
		et, ok, reason := g.translate(u.Elem())
		if !ok {
			return "", false, reason
		}
		switch u.Dir() {
		case types.SendOnly:
			return "SendChan<" + et + ">", true, ""
		case types.RecvOnly:
			return "RecvChan<" + et + ">", true, ""
		default:
			return "Channel<" + et + ">", true, ""
		}
	case *types.Pointer:
		// *NamedInThisPackage → the opaque handle of that name.
		if n, ok := u.Elem().(*types.Named); ok && n.Obj().Pkg() == g.pkg {
			return n.Obj().Name(), true, ""
		}
		return "", false, "pointer to a non-local or unnamed type"
	case *types.Named:
		if isErrorType(u) {
			return "error", true, ""
		}
		if u.Obj().Pkg() == g.pkg {
			return u.Obj().Name(), true, "" // a sibling handle, used by value
		}
		return "", false, "cross-package type " + u.Obj().Pkg().Path() + "." + u.Obj().Name()
	case *types.Interface:
		return "", false, "interface type (bind the concrete type, or model in an adapter)"
	default:
		return "", false, fmt.Sprintf("unsupported Go type %s", t.String())
	}
}

// translateBasic maps Go's predeclared scalar types; the bail list
// (uintptr, complex, unsafe.Pointer) returns ok=false.
func translateBasic(b *types.Basic) (string, bool, string) {
	switch b.Kind() {
	case types.Bool:
		return "bool", true, ""
	case types.Int:
		return "int", true, ""
	case types.Int8:
		return "int8", true, ""
	case types.Int16:
		return "int16", true, ""
	case types.Int32:
		return "int32", true, ""
	case types.Int64:
		return "int64", true, ""
	case types.Uint:
		return "uint", true, ""
	case types.Uint8:
		return "byte", true, ""
	case types.Uint16:
		return "uint16", true, ""
	case types.Uint32:
		return "uint32", true, ""
	case types.Uint64:
		return "uint64", true, ""
	case types.Float32:
		return "float32", true, ""
	case types.Float64:
		return "float64", true, ""
	case types.String:
		return "string", true, ""
	case types.UnsafePointer:
		return "", false, "unsafe.Pointer"
	case types.Uintptr:
		return "", false, "uintptr"
	case types.Complex64, types.Complex128:
		return "", false, "complex numbers"
	default:
		return "", false, "basic type " + b.String()
	}
}

// tideReserved mirrors lang-spec/keywords.md — Tide hard keywords and
// the boolean/unit literals. A generated identifier landing on one is
// escaped with a trailing `_`; the explicit `@go` attribute still pins
// the real Go symbol, so the rename is lossless. Tide-only keywords
// (match, scope, spawn, unit, this, extern, in, while, let) are the ones
// a Go name can legitimately collide with (Go's own keywords can't be Go
// identifiers, so they never reach here).
var tideReserved = map[string]bool{
	"import": true, "type": true, "class": true, "interface": true,
	"implements": true, "extends": true, "static": true,
	"func": true, "let": true, "const": true, "var": true,
	"if": true, "else": true, "for": true, "in": true, "while": true,
	"return": true, "match": true, "try": true, "defer": true,
	"spawn": true, "scope": true, "select": true, "break": true,
	"continue": true, "true": true, "false": true, "unit": true,
	"this": true, "extern": true,
}

// escapeKeyword appends `_` to a name that collides with a Tide reserved
// word, keeping it a legal identifier.
func escapeKeyword(s string) string {
	if tideReserved[s] {
		return s + "_"
	}
	return s
}

// tideName lowercases a Go exported name's first letter (the standard
// case convention) and escapes a keyword collision.
func tideName(goName string) string {
	if goName == "" {
		return goName
	}
	return escapeKeyword(strings.ToLower(goName[:1]) + goName[1:])
}

func paramName(p *types.Var, i int) string {
	if p.Name() != "" && p.Name() != "_" {
		return escapeKeyword(p.Name())
	}
	return fmt.Sprintf("a%d", i)
}

func isErrorType(t types.Type) bool {
	n, ok := t.(*types.Named)
	return ok && n.Obj().Name() == "error" && n.Obj().Pkg() == nil
}

func isBasicKind(t types.Type, k types.BasicKind) bool {
	b, ok := t.(*types.Basic)
	return ok && b.Kind() == k
}
