#!/usr/bin/env python3
"""Measure how far each example gets through the tide build pipeline.

Source of truth is ``examples/auto-status.json`` (deterministic — no
timestamps or commit SHAs, so it diffs cleanly). ``examples/STATUS.md``
is a human view generated from it. The metric we grow is ``build_ok``:
the number of examples that compile end-to-end.

    scripts/corpus_status.py            regenerate the JSON + STATUS.md
    scripts/corpus_status.py --check    fail if the snapshot is stale
                                        or if build_ok regressed (ratchet)
    scripts/corpus_status.py --history  derive the full trend from git
                                        (git log of auto-status.json) as JSONL

History is never maintained — git is the append-only log; --history
reconstructs it on demand, so there is no parallel file to drift.

Written in Python as interim dev tooling. The intent is to rewrite it
in Tide once feature-coverage is sufficient (subprocess, JSON, file
walking, string ops — all map onto Tide + Go-stdlib bindings), as a
self-hosting/dogfooding milestone. Kept deliberately straightforward
and idiom-light to make that port mechanical.
"""
from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
import tempfile

SCHEMA_VERSION = 1
JSON_PATH = "examples/auto-status.json"
MD_PATH = "examples/STATUS.md"

# Diagnostics emitted before a file parses; any other error code means
# the file parsed and a later stage rejected it.
PARSE_CODES = {"E0101", "E0102", "E0109", "E0110", "E0111", "E0112"}
EMIT_CODES = {"E0801", "E0802", "E0803"}
STAGE_ORDER = {"build": 0, "emit": 1, "sema": 2, "parse": 3}


def repo_root() -> str:
    return subprocess.check_output(
        ["git", "rev-parse", "--show-toplevel"], text=True
    ).strip()


def corpus_files() -> list[str]:
    files = []
    for root in ("examples", "user_tests"):
        for dirpath, _, names in os.walk(root):
            for n in names:
                if n.endswith(".td"):
                    files.append(os.path.join(dirpath, n).replace(os.sep, "/"))
    return sorted(files)


def build_tide(tmp: str) -> str:
    binpath = os.path.join(tmp, "tide")
    r = subprocess.run(
        ["go", "build", "-o", binpath, "./cmd/tide"],
        capture_output=True, text=True,
    )
    if r.returncode != 0:
        sys.exit(f"corpus-status: building tide failed:\n{r.stderr}")
    return binpath


def error_code(line: str) -> str:
    i = line.find("error[")
    if i < 0:
        return ""
    rest = line[i + len("error["):]
    j = rest.find("]")
    return rest[:j] if j >= 0 else ""


def first_error_line(out: str) -> str:
    for ln in out.splitlines():
        k = ln.find("error[")
        if k >= 0:
            return ln[k:].strip()  # strip "<path>:<line>:<col>: " position
    for ln in out.splitlines():
        if ln.strip():
            return ln.strip()
    return "unknown failure"


def classify(tide: str, file: str, out: str) -> tuple[str, str]:
    r = subprocess.run(
        [tide, "build", "-o", out, file],
        capture_output=True, text=True,
    )
    if r.returncode == 0:
        return "build", ""
    combined = (r.stdout or "") + (r.stderr or "")
    first = first_error_line(combined)
    code = error_code(first)
    if code in PARSE_CODES:
        return "parse", first
    if "go build failed" in combined or code in EMIT_CODES:
        return "emit", first
    if code:
        return "sema", first
    return "emit", first


def collect() -> dict:
    with tempfile.TemporaryDirectory(prefix="corpus-status-") as tmp:
        tide = build_tide(tmp)
        outp = os.path.join(tmp, "out")
        files = corpus_files()
        rows, tot = [], {"parse": 0, "sema": 0, "emit": 0, "build": 0}
        for f in files:
            stage, blocker = classify(tide, f, outp)
            rows.append({"path": f, "stage": stage, "blocker": blocker})
            tot[stage] += 1
    return {
        "schema_version": SCHEMA_VERSION,
        "totals": {
            "total": len(files),
            "parse_fail": tot["parse"],
            "sema_fail": tot["sema"],
            "emit_fail": tot["emit"],
            "build_ok": tot["build"],
        },
        "files": rows,
    }


def dumps(status: dict) -> str:
    return json.dumps(status, indent=2, ensure_ascii=False) + "\n"


def render_markdown(s: dict) -> str:
    t = s["totals"]
    out = [
        "# Example conformance status\n",
        "Generated by `scripts/corpus_status.py` from "
        "`examples/auto-status.json` — do not edit by hand. "
        "Run `scripts/corpus_status.py` to refresh.\n",
        f"**{t['build_ok']} / {t['total']} examples build end-to-end.**\n",
        "| Stage reached | Count |",
        "|---|---|",
        f"| ✅ build (full pipeline) | {t['build_ok']} |",
        f"| emit / codegen fail | {t['emit_fail']} |",
        f"| sema fail | {t['sema_fail']} |",
        f"| parse fail | {t['parse_fail']} |",
        "",
        "## Per-example\n",
        "| Example | Stage | First blocker |",
        "|---|---|---|",
    ]
    rows = sorted(s["files"], key=lambda f: (STAGE_ORDER[f["stage"]], f["path"]))
    for f in rows:
        out.append(f"| `{f['path']}` | {f['stage']} | {f['blocker'] or '—'} |")
    return "\n".join(out) + "\n"


def write_artifacts(s: dict) -> None:
    with open(JSON_PATH, "w") as fh:
        fh.write(dumps(s))
    with open(MD_PATH, "w") as fh:
        fh.write(render_markdown(s))


def cmd_check(cur: dict) -> int:
    try:
        committed = json.load(open(JSON_PATH))
    except FileNotFoundError:
        print(f"corpus-status: {JSON_PATH} missing — run scripts/corpus_status.py", file=sys.stderr)
        return 1
    cb, ab = committed["totals"]["build_ok"], cur["totals"]["build_ok"]
    if ab < cb:
        print(f"corpus-status: REGRESSION: build_ok dropped {cb} -> {ab} — "
              "a previously-building example no longer builds", file=sys.stderr)
        return 1
    if dumps(cur).strip() != dumps(committed).strip():
        print(f"corpus-status: snapshot stale (committed build_ok={cb}, actual={ab}) — "
              "run scripts/corpus_status.py and commit the result", file=sys.stderr)
        return 1
    try:
        md = open(MD_PATH).read()
    except FileNotFoundError:
        md = None
    if md != render_markdown(cur):
        print(f"corpus-status: {MD_PATH} stale — run scripts/corpus_status.py and commit", file=sys.stderr)
        return 1
    print(f"corpus-status: up to date ({ab}/{cur['totals']['total']} build)")
    return 0


def cmd_history() -> int:
    log = subprocess.check_output(
        ["git", "log", "--reverse", "--format=%H%x09%cI%x09%s", "--", JSON_PATH],
        text=True,
    )
    for ln in log.splitlines():
        if not ln.strip():
            continue
        sha, date, subject = ln.split("\t", 2)
        try:
            blob = subprocess.check_output(["git", "show", f"{sha}:{JSON_PATH}"], text=True)
            s = json.loads(blob)
        except (subprocess.CalledProcessError, json.JSONDecodeError):
            continue
        t = s["totals"]
        print(json.dumps({
            "date": date, "commit": sha[:12], "subject": subject,
            "total": t["total"], "build_ok": t["build_ok"],
            "emit_fail": t["emit_fail"], "sema_fail": t["sema_fail"],
            "parse_fail": t["parse_fail"],
        }, ensure_ascii=False))
    return 0


def main() -> int:
    ap = argparse.ArgumentParser(description="tide example conformance scoreboard")
    ap.add_argument("--check", action="store_true", help="fail if snapshot stale or build_ok regressed")
    ap.add_argument("--history", action="store_true", help="emit the trend (JSONL) from git history")
    args = ap.parse_args()

    os.chdir(repo_root())

    if args.history:
        return cmd_history()

    cur = collect()
    if args.check:
        return cmd_check(cur)
    write_artifacts(cur)
    t = cur["totals"]
    print(f"corpus-status: wrote {JSON_PATH} + {MD_PATH} ({t['build_ok']}/{t['total']} build)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
